### ISSUE TITLE
can't add RSS feed

### ISSUE THREAD

**Issue by schiesbn** [owncloud/news#931] opened 2016-02-25 11:17 UTC
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem

I can't add this RSS feed: https://edri.org/feed/

I get this error message:

````
Feed not found: either the website does not provide a feed or blocks access. To rule out blocking, try to download the feed on your server's command line using curl: curl http://the-feed.tld
````

`curl https://edri.org/feed/` works just fine

Other feeds seems to work just fine. Don't know what's different.

## Steps to Reproduce
1. Go to the news app
2. Try to subscribe to https://edri.org/feed

## System Information
* News app version: 7.1.2
* ownCloud version: 8.2.2
* PHP version: 5.6.17

## Contents of owncloud/data/owncloud.log

```
{"reqId":"ZnAyS9By9AC\/8o0p3cc3","remoteAddr":"95.112.219.178","app":"news","message":"Feed not found: either the website does not provide a feed or blocks access. To rule out blocking, try to download the feed on your server's command line using curl: curl http:\/\/the-feed.tld","level":0,"time":"2016-02-25T11:12:00+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
```

**Comment by BernhardPosselt** [comment] 2016-02-25 11:30
curl times out on my server, so does php -f vendor/fguillot/picofeed/picofeed feed https://edri.org/feed

**Comment by BernhardPosselt** [comment] 2016-02-25 11:32
Hetzner?

**Comment by BernhardPosselt** [comment] 2016-02-25 11:37
BTW I highly suspect that this is not a News app issue but the problem is the feed.

**Comment by BernhardPosselt** [comment] 2016-02-25 16:48
Yes, feed also times out on another machine with curl, closing

**Comment by schiesbn** [comment] 2016-02-25 16:59
@BernhardPosselt the feed needs trailing slash... Try `curl https://edri.org/feed/`

Maybe that's also the problem regarding the news app. Does it always remove trailing slashes?

**Comment by BernhardPosselt** [comment] 2016-02-25 17:06
No, trailing slashes are not removed. Still getting timeouts though btw. Apart from that the / should not matter, please contact the feed author

**Comment by schiesbn** [comment] 2016-02-25 17:11
Every other news reader I tried can read the feed just fine. So don't think it is a general issue with the feed.

For me also both commands work `curl https://edri.org/feed/` and `php -f vendor/fguillot/picofeed/picofeed feed https://edri.org/feed`

**Comment by BernhardPosselt** [comment] 2016-02-25 17:17
Feed is passed as is to picofeed, try logging out the url before this statement https://github.com/owncloud/news/blob/master/fetcher/feedfetcher.php#L81 and you will see it contains the slash. 

If at all this is a picofeed issue :)

**Comment by BernhardPosselt** [comment] 2016-02-25 17:20
Ok, got it to work, it's this issue: https://github.com/owncloud/news#im-getting-a-feed-not-found-error-when-adding-a-feed-but-it-works-in-picofeedminiflux

**Comment by BernhardPosselt** [comment] 2016-02-25 17:20
Apart from the weird shit with the trailing / :D

**Closed by BernhardPosselt** 2016-02-25 17:20 UTC
Labels: Needs info

**Comment by schiesbn** [comment] 2016-02-26 10:15
@BernhardPosselt setting the user agent to "test" worked, I get in contact with the side admin and ask if they can do anything about it.

Does this happen often? If yes, wouldn't it make sense to identify as a more generic user agent which is accepted by all feed providers? Just thinking...

**Comment by BernhardPosselt** [comment] 2016-02-26 10:17
I'm not sure how often it happens. Since we switched to picofeed we've had 3-4 reports AFAIK (including yours).

The current user agent string was proposed by a guy at (probably) feedburner. It would be interesting to see what character exactly causes the problem, our user agent is not that different from other user agents. Can you investigate?
