### ISSUE TITLE
Unable to enable news on owncloud 9.1

### ISSUE THREAD

**Issue by theScrabi** [owncloud/news#1010] opened 2016-07-22 15:39 UTC
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
What problem did you encounter?
Enable the app, but after reload app is disabled again.

## Steps to Reproduce
Explain what you did to encounter the issue
1. Go to not active apps
2. enable news
3. reload page

## System Information
* News app version: 8.8.0
* ownCloud version: 9.1.0.15
* PHP version: 7.0.8
* Database and version: mysql 5.7.13
* Browser and version: firefox
* Distribution and version: ubuntu 16.04 aarch64

## Contents of owncloud/data/owncloud.log

```json

{"reqId":"6NRytvg5sb2dV0ZT05rb","remoteAddr":"188.194.240.199","app":"no app in context","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class '\\\\OCP\\\\Backgroundjob' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/appinfo\\\/application.php(243): OCA\\\\News\\\\Config\\\\AppConfig->registerAll()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/appinfo\\\/app.php(18): OCA\\\\News\\\\AppInfo\\\\Application->registerConfig()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(186): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(149): OC_App::requireAppFile('news')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('news')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(875): OC_App::loadApps()\\n#6 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php\",\"Line\":88}","level":3,"time":"2016-07-22T15:27:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files","user":"admin"}
{"reqId":"ha+KezzrF\/kcWpRq7W\/X","remoteAddr":"188.194.240.199","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-07-22T15:28:04+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"ha+KezzrF\/kcWpRq7W\/X","remoteAddr":"188.194.240.199","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-07-22T15:28:08+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"ha+KezzrF\/kcWpRq7W\/X","remoteAddr":"188.194.240.199","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-07-22T15:28:08+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}

```

**Comment by Gerii** [comment] 2016-07-22 15:51
Duplicate of #1008

**Closed** 2016-07-22 16:05 UTC
