### ISSUE TITLE
ads in news feed?

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/news#816] opened 2015-06-19 00:55 UTC
Since the last week I have some ads in my news feed. Especialy from : http://rss.radio-canada.ca/fils/nouvelles/nouvelles.xml

like: http://screencloud.net/v/hGN7

**Comment by Raydiation** [comment] 2015-06-19 07:38
So the feed decided to ship ads. Use an ad blocker?

**Comment by thenamelessthing** [comment] 2015-06-19 10:18
Hi already use adblock.. How can I be certain it's the feed and not news or
chrome are not infected?

Patrick Gagné

**Comment by Raydiation** [comment] 2015-06-19 10:25
Cant reproduce the issue with turned on ad blocker. 

> How can I be certain it's the feed and not news or chrome are not infected?

Read the source code.

This is not really a news app issue that is related to a news app bug or feature, therefore closing.

**Closed by Raydiation** 2015-06-19 10:25 UTC
