### ISSUE TITLE
No feedback if OPML import contains no feeds or folders

### ISSUE THREAD

**Issue by dbeniamine** [owncloud/news#924] opened 2016-02-14 22:17 UTC
Hi,

I had troubles importing an `.opml` file into owncloud new application. After a while wondering why nothing was happening I realized that I was importing a wrong file which was not an opml file. Sadly Owncloud didn't tell me about my mistake.

David

**Comment by BernhardPosselt** [comment] 2016-02-15 08:42
Method is here: https://github.com/owncloud/news/blob/master/js/service/OPMLParser.js#L60

We should validate it, and if needed throw an exception which is caught here:
https://github.com/owncloud/news/blob/master/js/controller/SettingsController.js#L77

Should we use an alert for showing the error message? 

@cosenal @jancborchardt any ideas on how to show proper feedback?

**Comment by dbeniamine** [comment] 2016-02-15 12:40
I haven't looked at the code, but when we provide a badly formatted `.opml` file Owncloud shows an error message near the import button, I guess it seems reasonable to show a "Bad file format" error at the same place.

**Comment by jancborchardt** [comment] 2016-02-15 13:07
Yep, good suggestion. A slightly better error message could be »Wrong file format. Please choose an OPML file.«?

**Comment by BernhardPosselt** [comment] 2016-02-21 20:05
Ok, after going through the issues I can not reproduce it. If I upload an invalid OPML file I'm getting: Error when importing: file does not contain valid OPML

**Comment by dbeniamine** [comment] 2016-02-21 21:24
It happened to me while uploading a `.gpx`  file (`export.gpx`, instead of `export.opml`) which occurs to be a correct xml file. I guess that New parses the xml correctly but does nothing as the file does not contain any opml entries.

[ There is](https://github.com/owncloud/news/files/139874/export.txt) (almost) empty gpx file (renamed export.txt because of github limitations) whith which the bug occurs.

I'm running News 6.1.1 over Owncloud 8.2.2 installed from the Owncloud repositories on a Debian stable with Apache 2.4.10, Php 5.6.17-0 and Mysql 5.5.47-0.

I hope this is enough info to reproduce the bug.

**Comment by BernhardPosselt** [comment] 2016-02-22 09:13
Ok, so the solution is basically to show an error message if no feeds or folders are found

**Comment by dbeniamine** [comment] 2016-02-22 13:03
I agree, but I guess there are two distinct errors:

+ Bad file format (valid xml but no <ompl> tag)
+ No feeds or folder found (valid xml with <ompl> tag but empty)

I think that those two errors are quite different: the first is a bad manipulation from the user, while the second might come from a BUG on the tools used to generate the OMPL export.

**Comment by BernhardPosselt** [comment] 2016-02-27 15:17
Marking this as a junior bug because its very easy to fix and a low priority bug :)

Pointers:
The parsedContent variable here: https://github.com/owncloud/news/blob/master/js/controller/SettingsController.js#L42

is a javascript object that has a list of feeds and folders:

```js
{feeds: [], folders: []}
```

All that needs to be done is to test if both of them are of length 0 and then throw an exception (which will be caught here: https://github.com/owncloud/news/blob/master/js/controller/SettingsController.js#L76)

The error message also needs to be improved to reflect the additional erorr state: https://github.com/owncloud/news/blob/master/templates/part.settings.php#L97 by simply adding the additional failure cause or by adding a new type of error on the settings controller.

The JavaScript needs to be compiled using gulp, instructions are here https://github.com/owncloud/news/tree/master/js#javascript-development

**Closed** 2016-04-08 17:35 UTC
Labels: Bug, Contributors Needed, Easy, JavaScript
