### ISSUE TITLE
After exiting from full-screen video player (eg: youtube), autoscroll to the start of feed

### ISSUE THREAD

**Issue by rakshazi** [owncloud/news#921] opened 2016-02-03 13:25 UTC
Hello!

## Enviroment

Owncloud 8.2.2
News 7.1.1
Chrome 48.0.2564.97 (64-bit)
PHP 7.0.2-4+deb.sury.org~trusty+1 (cli) ( NTS )
Ubuntu 14.04.xx

## Problem

First of all, sorry for my bad English, but I hope that you will understand me.

**How to reproduce**

Find any entry (not in the start of feed) in OwnCloud News items with youtube, vimeo or vk (or any other, but tested only on these players) video player, open video in fullscreen mode and watch it (or just click play) and then exit fullscreen mode (press Esc), you will see that you moved to start of news feed when you opened full screen mode.

**Expected behavior**

User must stay at the same entry in feed (at the same place) after exit from video player full screen mode.

Best regards,
Nikita.

pS: Affects both Flash Player video players and html5 video players

**Comment by BernhardPosselt** [comment] 2016-02-03 13:44
Can reproduce, but only in Chrome, Firefox does not behave like this.

**Comment by BernhardPosselt** [comment] 2016-02-03 13:45
Chrome bug, see https://code.google.com/p/chromium/issues/detail?id=142427

**Comment by BernhardPosselt** [comment] 2016-02-03 13:46
Looks like its resolved in the latest unstable build

**Closed by BernhardPosselt** 2016-02-03 13:45 UTC

**Comment by rakshazi** [comment] 2016-02-03 14:45
@BernhardPosselt thank you for info!
