### ISSUE TITLE
News 8.1.0 is provided as update for 8.2.x users

### ISSUE THREAD

**Issue by RealRancor** [owncloud/news#958] opened 2016-03-31 10:11 UTC
Hi,

seems that the News app version 8.0.0 is provided for 8.2.x Users running 7.1.2. I got the Update Button and the appstore is also reporting 8.0.0 as current for 8.2.3:

https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=920&approved=all

I don't know if this is an issue of the app release at:

https://apps.owncloud.com/content/show.php/News?content=168040

(The download button says "All Versions") or the appstore itself so reporting this first here.

I'm also not quite sure if this is related to https://github.com/owncloud/appstore-issues/issues/50.

**Comment by BernhardPosselt** [comment] 2016-03-31 10:54
Basically #953

**Comment by BernhardPosselt** [comment] 2016-03-31 10:54
Same root cause

**Comment by BernhardPosselt** [comment] 2016-03-31 18:27
Can you test again? Seems to be the correct download now.

**Comment by BernhardPosselt** [comment] 2016-03-31 18:27
Maybe the appstore caches really hard

**Comment by BernhardPosselt** [comment] 2016-04-02 19:52
I've reverted the version in the app store to 7.1.2. If the app store issue is fixed, I'll reupload the latest version. Closing this issue

**Closed by BernhardPosselt** 2016-04-02 19:52 UTC
Labels: Support

**Comment by RealRancor** [comment] 2016-04-02 21:52
@BernhardPosselt Sorry, missed this. But it might be enough to just provide 7.1.2 for oC 8.2 and 8.1.0 in the right order as seen here: https://github.com/owncloud/calendar/issues/308

**Comment by BernhardPosselt** [comment] 2016-04-03 09:03
Ah, @RealRancor thanks for that hint. I've added a specific version to the download link (used to just add "all versions"). The upload is still not fixed, but the link to the github release tar.gz seems to work.

**Comment by RealRancor** [comment] 2016-04-03 16:06
@BernhardPosselt 8.1.0 is provided again for oC 8.2.3.

I think this could be easily solved if you're also uploading 7.1.2 for 8.2 and the matching versions for 8.1 and 8.0

**Comment by BernhardPosselt** [comment] 2016-04-03 16:21
Aw, damnit. I've explicitely set 9.0.

The thing is: If I upload a version for 8.2 people will expect support/bugfixes. What do you think?

**Comment by BernhardPosselt** [comment] 2016-04-03 18:01
Ah right, this is a bug in core, please take this issue there ;)

**Comment by RealRancor** [comment] 2016-04-03 19:50
You mean: https://github.com/owncloud/core/issues/23089 Not quite sure if this is the same issue?

**Comment by BernhardPosselt** [comment] 2016-04-03 20:06
Most likely not. Just a guess though
