### ISSUE TITLE
Separate feed for "read later" items?

### ISSUE THREAD

**Issue by David-Guillot** [owncloud/news#892] opened 2015-11-21 11:32 UTC
Hi,

I come from TinyTinyRSS and I find OwnCloud News very convenient except one thing : there is only one way to mark as item (to star it).

Here is what I was doing in TTRSS: browsing a lot of items, I see an interesting title, I use the favorite queue to mark it to be read later, and then when I read it, if I find it very interesting, there is another queue in TTRSS called "published" where I put all items I want to keep on the long term.

With OwnCloud News, I could do the same by keeping items i want to read later as unread, and use the favorites to keep items on the long term, but I then wouldn't be able to use the "mark all as read" feature because it would mark my old items that I want to read later as read. This is why I'd like to have a dedicated queue where i could store items I want to "read later".

I hope I'm making myself clear enough, let me know if I'm not. I also hope other people could use such a feature ;)
Thanks

**Comment by BernhardPosselt** [comment] 2015-11-21 12:40
Have you tried to simply star it? Works fine for me. BTW: TT-RSS users seem to be the only ones complaining about this, so I suspect this is just a habit.

**Comment by David-Guillot** [comment] 2015-11-21 18:10
Actually yes, I did try the following scenario:
1/ I'm browsing an RSS feed that has unread items ; I'm browsing only titles, so nothing is mark as read
2/ I star one item that I want to read later
3/ I click on "mark all items as read" for this RSS feed
4/ Then the item I just starred is marked as read also in my favorites ; so I can't find it easily in my favorites because it's mixed with other items I starred after reading them because I want to bookmark them

This is why IMHO a "Read later" feature would be useful: it would allow you to use "mark this whole feed as read" (because it's fast) even when you found something interesting that you don't have time to read right now. It's very different than "starring" an item that you already read and want to bookmark.

**Comment by BernhardPosselt** [comment] 2015-11-22 19:26
Your opinion on this? @Bugsbane @IBBoard @cwmke @kgraefe @ogasser @vgezer @cosenal @MorrisJobke @LukasReschke

**Comment by kgraefe** [comment] 2015-11-22 20:00
The news app is not a bookmark app, is it?

**Comment by IBBoard** [comment] 2015-11-22 20:01
This sounds a bit like my ticket #490, which I was basically told was obscure desired behaviour and I'd just have to live with how it worked (paraphrasing slightly there 😉). I might have come from a slightly different angle and been less clear on explaining it, though.

For now, I do just what David proposed as the only OwnCloud News option - leave it as unread if I might read it later, and star it once I know it is good. Having a separate "read later" or "read lock" (which prevents something being marked as read with "Mark all as read") would be a more accurate way to deal with how I read my feed.

**Comment by kgraefe** [comment] 2015-11-22 20:35
> @kgraefe Depends what your news feeds contain, surely? If it is pure news (like BBC News, or an application's release history) then probably not, but if it is long-form articles then why not? Why go somewhere else when there's no need?

Because that is what bookmark managers can do better by supporting tags or directory structures. In your analogy, shelf 2 will become a mess after some time. Plus, you cannot (easily) store books and articles from outside the RSS world in shelf 1. So you probably need a separate shelf anyway...

**Comment by IBBoard** [comment] 2015-11-22 20:46
The problem is that bookmarks only store a location. OwnCloud News stores the whole article (or at least as much of the article as the RSS feed publishes - which is all of it 9 out of 10 of the feeds I have). Link rot happens surprisingly frequently online. If you've got a system for holding your newspapers, why not have it keep the interesting clippings as well? 

Also, from what you're saying then we should get rid of the star as well, because if you star it because it is interesting then you should just visit the page and bookmark it anyway.

**Comment by kgraefe** [comment] 2015-11-22 20:50
Staring means "read it later" to me. When I read it and I find that the article may be useful in the future, I bookmark it.

**Comment by cwmke** [comment] 2015-11-22 21:13
It might be worthwhile to add an archive folder instead of just stars.  I imagine this is something useful for a good sized group of users.  Personally I use stars for an article I'm going to look at (or fix) later and then unstar it after coming back and finnishing.

I do miss some of the advanced features of tt-rss but I think that keeping the base news app simple and setting up a healthy plugin system is the better route long-term.  The "read lock" idea mentioned by @IBBoard is a good example of functionality I think should be added by a plugin.  But that's just my opinion.  :-)

**Comment by BernhardPosselt** [comment] 2015-11-22 21:49
Hm, good points, I did not actually think about it that way yet: I agree with @kgraefe that the News app is not good at archiving articles. 

First of all, it updates the articles (which makes sense for a News reader if you ask me) so it may overwrite content that you initially wanted to bookmark. 

Second, although it has built in full text feed capabilities that fetch the content from the website it is  turned off by default and you can't enable it for older articles that don't show up in the feed anymore. Enabling it for all articles slows down the update significantly and it may result in worse content, so the opt-in makes sense from my POV.

Rather than turning the app into a bookmark app, we should outsource it to a real bookmark app which is really good at performing that task. The News app itself can then be adapted with a very simple plugin (if you need help ask me ;D) that interfaces with the bookmarks app.

**Closed** 2015-11-23 08:27 UTC
Labels: Discussion, Enhancement

**Comment by BernhardPosselt** [comment] 2015-11-23 19:08
I've added a section in the Wiki for existing and requested plugins https://github.com/owncloud/news/wiki#requested-and-needs-contributors and already added a bookmarks integration plugin https://github.com/owncloud/news/wiki/Bookmarks-Plugin

**Comment by BernhardPosselt** [comment] 2015-11-23 19:09
If someone wants to take a stab at it, feel free to ask for help!
